---
Name: sisconfig
After: 'framework/*','cms/*'
---
AssetAdmin:
  extensions:
    - AssetAdminSyncFilesExtension
DBField:
  extensions:
   - RichLinksExtension
SiteTree:
  extensions:
    - SiteTreeTaxonomyExtension
    - MetadataExtension
    - PageThumbnailExtension
SiteTree:
  extensions:
    - ChangeRecordable
File:
  extensions:
    - ChangeRecordable
Site:
  extensions:
   - SISSite
Block:
  extensions:
    - MultisitesAware
BlockSet:
  extensions:
    - MultisitesAware
FileField:
  extensions:
    - MultisitesFileFieldExtension
HtmlEditorField_Toolbar:
  extensions:
    - MultisitesHtmlEditorField_ToolbarExtension
Link:
  extensions:
    - LinkExtension
TaxonomyTerm:
  extensions:
   - TaxonomyTermExtension
PaginatedList:
  extensions:
    - PaginatedListIterationExtension
MetadataField:
  extensions:
   - AGLSMetadataFieldExtension
File:
  extensions:
    - SISFileExtension
GDBackend:
  default_quality: 90
Session:
  timeout: 3600
LeftAndMain:
  session_keepalive_ping: false
  menu_groups:
    Administration:
      - ReportAdmin
      - SecurityAdmin
      - DataChangeAdmin
      - QueuedJobsAdmin
      - TimedNoticeAdmin
      - AdvancedWorkflowAdmin
  extra_requirements_css:
    ba-sis/css/cms-custom.css:
      media: all
PasswordField:
  autocomplete: false
Security:
  login_recording: true
Member:
  lock_out_after_incorrect_logins: 5
  lock_out_delay_mins: 15
